print("Hello world")
#print(input("where are you going?"))
two_digit_number = input("Enter any two digit number: \n")
num_f = int(two_digit_number[0])
num_s = int(two_digit_number[1])
print(num_f+num_s)
print(type(two_digit_number))
print(len(two_digit_number))